# Build stage
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY package-lock.json ./
RUN npm ci

COPY . .
RUN npx tsc

# Runtime stage
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY package-lock.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

COPY .env .
COPY serviceAccountKey.json .

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "dist/index.js"]
