services:
  backend:
    build:
      context: "."
      dockerfile: ".Dockerfile-dev"
    image: mybackend:latest
    ports:
      - "8080:3000"
  mongo:
    image: mongo
    command: --port ${MONGO_PORT:-27017}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-password}
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:  ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-password}@mongo:${MONGO_PORT:-27017}/MONGO_USER:-adminMONGO_USER:-admin
      ME_CONpIG_BASICAUTH: false
